- hosts: all
  gather_facts: no
  tasks:
    - name: Check if Python 3 is available
      stat:
        path: /usr/bin/python3
      register: python3_check

    - name: Set Python interpreter to Python 3 if available, otherwise fallback to Python 2
      set_fact:
        ansible_python_interpreter: "{{ '/usr/bin/python3' if python3_check.stat.exists else '/usr/bin/python' }}"

    - name: Verify pod status on master nodes
      check_pod_status:
        kubeconfig: "{{ kubernetes.kubeconfig }}"
        pod_name_regex: "{{ item }}"
        node_name: "master01.local"
        timeout: "{{ kubernetes.monitor.timeout }}"
      loop: "{{ kubernetes.monitor.master_pods }}"
      delegate_to: "{{ groups['first_master'][0] }}"
      when: "'first_master' in group_names or 'other_master' in group_names"
