#--------------------------------------------------------------------------------

- name: Gather info about the servers
  hosts: first_master, other_master, worker
  become: yes
  roles:
    - first_gather_info

#--------------------------------------------------------------------------------

- name: Pre-task upgrade kubernetes to 1.22
  hosts: first_master, other_master, worker
  become: yes
  gather_facts: false
  vars:
    current_target_version: 22
  roles:
    - gather_info
    - pre_upgrade

- name: Upgrade kubernetes version to 1.22 (if kubelet version is less than 1.22)
  hosts: first_master, other_master, worker
  serial: 1
  become: yes
  gather_facts: false
  vars:
    current_target_version: 22
  roles:
    - upgrade

#--------------------------------------------------------------------------------

- name: Pre-task upgrade kubernetes to 1.23
  hosts: first_master, other_master, worker
  become: yes
  gather_facts: false
  vars:
    current_target_version: 23
  roles:
    - gather_info
    - pre_upgrade

- name: Upgrade kubernetes version to 1.23 (if kubelet version is less than 1.23)
  hosts: first_master, other_master, worker
  serial: 1
  become: yes
  gather_facts: false
  vars:
    current_target_version: 23
  roles:
    - upgrade

#--------------------------------------------------------------------------------

- name: Pre-task upgrade kubernetes to 1.24
  hosts: first_master, other_master, worker
  become: yes
  gather_facts: false
  vars:
    current_target_version: 24
  roles:
    - gather_info
    - pre_upgrade

- name: Upgrade kubernetes version to 1.24 (if kubelet version is less than 1.24)
  hosts: first_master, other_master, worker
  serial: 1
  become: yes
  gather_facts: false
  vars:
    current_target_version: 24
  roles:
    - upgrade

#--------------------------------------------------------------------------------

- name: Pre-task upgrade kubernetes to 1.25
  hosts: first_master, other_master, worker
  become: yes
  gather_facts: false
  vars:
    current_target_version: 25
  roles:
    - gather_info
    - pre_upgrade

- name: Upgrade kubernetes version to 1.25 (if kubelet version is less than 1.25)
  hosts: first_master, other_master, worker
  serial: 1
  become: yes
  gather_facts: false
  vars:
    current_target_version: 25
  roles:
    - upgrade

#--------------------------------------------------------------------------------

- name: Pre-task upgrade kubernetes to 1.26
  hosts: first_master, other_master, worker
  become: yes
  gather_facts: false
  vars:
    current_target_version: 26
  roles:
    - gather_info
    - pre_upgrade

- name: Upgrade kubernetes version to 1.26 (if kubelet version is less than 1.26)
  hosts: first_master, other_master, worker
  serial: 1
  become: yes
  gather_facts: false
  vars:
    current_target_version: 26
  roles:
    - upgrade

#--------------------------------------------------------------------------------

- name: Pre-task upgrade kubernetes to 1.27
  hosts: first_master, other_master, worker
  become: yes
  gather_facts: false
  vars:
    current_target_version: 27
  roles:
    - gather_info
    - pre_upgrade

- name: Upgrade kubernetes version to 1.27 (if kubelet version is less than 1.27)
  hosts: first_master, other_master, worker
  serial: 1
  become: yes
  gather_facts: false
  vars:
    current_target_version: 27
  roles:
    - upgrade

#--------------------------------------------------------------------------------

- name: Pre-task upgrade kubernetes to 1.28
  hosts: first_master, other_master, worker
  become: yes
  gather_facts: false
  vars:
    current_target_version: 28
  roles:
    - gather_info
    - pre_upgrade

- name: Upgrade kubernetes version to 1.28 (if kubelet version is less than 1.28)
  hosts: first_master, other_master, worker
  serial: 1
  become: yes
  gather_facts: false
  vars:
    current_target_version: 28
  roles:
    - upgrade

#--------------------------------------------------------------------------------

- name: Pre-task upgrade kubernetes to 1.29
  hosts: first_master, other_master, worker
  become: yes
  gather_facts: false
  vars:
    current_target_version: 29
  roles:
    - gather_info
    - pre_upgrade

- name: Upgrade kubernetes version to 1.29 (if kubelet version is less than 1.29)
  hosts: first_master, other_master, worker
  serial: 1
  become: yes
  gather_facts: false
  vars:
    current_target_version: 29
  roles:
    - upgrade
#--------------------------------------------------------------------------------

- name: Pre-task upgrade kubernetes to 1.30
  hosts: first_master, other_master, worker
  become: yes
  gather_facts: false
  vars:
    current_target_version: 30
  roles:
    - gather_info
    - pre_upgrade

- name: Upgrade kubernetes version to 1.30 (if kubelet version is less than 1.30)
  hosts: first_master, other_master, worker
  serial: 1
  become: yes
  gather_facts: false
  vars:
    current_target_version: 30
  roles:
    - upgrade








