- name: Get the kubelet version
  shell: "kubelet --version | cut -d. -f2"
  register: kubelet_version_raw
  changed_when: false

- name: Get the kubeadm version
  shell: "kubeadm version -o yaml | grep minor | cut -d'\"' -f2"
  register: kubeadm_version_raw
  changed_when: false

- name: Each node kubeadm version variable
  set_fact:
    kubeadm_version: "{{ kubeadm_version_raw.stdout_lines.0  }}"

- name: Each node kubelet version variable
  set_fact:
    kubelet_version: "{{ kubelet_version_raw.stdout_lines.0  }}"

###################################################################################################################

- name: Get all nodes name
  delegate_to: "{{ groups['first_master'][0] }}"
  shell: "KUBECONFIG={{ kubeconfig }} kubectl get node -o wide"
  register: k8s_nodes_raw
  changed_when: false

- name: Variable for storing "kubectl get node -o wide" command output
  set_fact:
    nodes: "{{ hostvars[groups['first_master'][0]].k8s_nodes_raw.stdout }}"

- name: Get this node's name
  shell: "echo -e '{{ nodes }}' | grep -E '({{ ansible_locally_reachable_ips.ipv4 | join('|') }})' | awk '{print $1}'"
  register: k8s_node_name_raw
  changed_when: false

- name: This server's kubernetes node name
  set_fact:
    k8s_node_name: "{{ k8s_node_name_raw.stdout_lines.0 }}"

###################################################################################################################

- debug:
    msg: 
      - "Node: {{ k8s_node_name }}, kubeadm version: {{ kubeadm_version }}, kubelet version: {{ kubelet_version }}"