# ----- SET NODE UPGRADE STATUS
- name: Initialize node upgrade status
  ansible.builtin.set_fact:
    gather_done: false

# ----- GET KUBEADM VERSION
- name: Retrieve kubeadm version
  block:
    - name: Execute kubeadm version command
      ansible.builtin.shell: "kubeadm version -o yaml | grep minor | cut -d'\"' -f2"
      register: kubeadm_version_raw
      retries: 5
      delay: 3
      changed_when: false
      failed_when: kubeadm_version_raw.rc != 0

    - name: Set kubeadm_version fact
      ansible.builtin.set_fact:
        kubeadm_version: "{{ kubeadm_version_raw.stdout_lines[0] }}"

# ----- GET KUBELET VERSION
- name: Retrieve kubelet version
  block:
    - name: Execute kubelet version command
      ansible.builtin.shell: "kubelet --version | cut -d. -f2"
      register: kubelet_version_raw
      retries: 5
      delay: 3
      changed_when: false
      failed_when: kubelet_version_raw.rc != 0

    - name: Set kubelet_version fact
      ansible.builtin.set_fact:
        kubelet_version: "{{ kubelet_version_raw.stdout_lines[0] }}"

# ----- GET K8S NODE NAME
- name: Determine Kubernetes node name
  block:
    - name: Retrieve all node names
      ansible.builtin.shell: "KUBECONFIG={{ kubernetes.kubeconfig }} kubectl get node -o wide"
      delegate_to: "{{ groups['first_master'][0] }}"
      register: k8s_nodes_raw
      changed_when: false
      failed_when: k8s_nodes_raw.rc != 0

    - name: Store kubectl output
      ansible.builtin.set_fact:
        nodes: "{{ hostvars[groups['first_master'][0]].k8s_nodes_raw.stdout }}"

    - name: Extract this node's name
      ansible.builtin.shell: "echo -e '{{ nodes }}' | grep -E '({{ ansible_locally_reachable_ips.ipv4 | join('|') }})' | awk '{print $1}'"
      register: k8s_node_name_raw
      changed_when: false
      failed_when: k8s_node_name_raw.rc != 0

    - name: Set k8s_node_name fact
      ansible.builtin.set_fact:
        k8s_node_name: "{{ k8s_node_name_raw.stdout_lines[0] }}"

# ----- DEBUG ALL GATHERED VARIABLES
- name: Display gathered Kubernetes information
  ansible.builtin.debug:
    msg: 
      - "Node: {{ k8s_node_name }}"
      - "  - Kubeadm version: {{ kubeadm_version }}"
      - "  - Kubelet version: {{ kubelet_version }}"