- name: Get the kubelet version
  shell: "kubelet --version | cut -d. -f2"
  register: kubelet_version_raw
  changed_when: false

- name: Get the kubeadm version
  shell: "kubeadm version -o yaml | grep minor | cut -d'\"' -f2"
  register: kubeadm_version_raw
  changed_when: false

- name: Each node kubeadm version variable
  set_fact:
    kubeadm_version: "{{ kubeadm_version_raw.stdout_lines.0  }}"

- name: Each node kubelet version variable
  set_fact:
    kubelet_version: "{{ kubelet_version_raw.stdout_lines.0  }}"

###################################################################################################################

- debug:
    msg: 
      - "Node: {{ k8s_node_name }}, kubeadm version: {{ kubeadm_version }}, kubelet version: {{ kubelet_version }}"