# ----- GET KUBEADM VERSION
- name: Get $kubeadm_version
  block:
    - name: Get the kubeadm version
      shell: "kubeadm version -o yaml | grep minor | cut -d'\"' -f2"
      register: kubeadm_version_raw
      retries: 3
      delay: 3
      changed_when: false

    - name: Set $kubeadm_version
      set_fact:
        kubeadm_version: "{{ kubeadm_version_raw.stdout_lines.0  }}"

# ----- GET KUBELET VERSION
- name: Get $kubelet_version
  block:
    - name: Get the kubelet version
      shell: "kubelet --version | cut -d. -f2"
      register: kubelet_version_raw
      retries: 3
      delay: 3
      changed_when: false

    - name: Set $kubelet_version
      set_fact:
        kubelet_version: "{{ kubelet_version_raw.stdout_lines.0  }}"

# ----- DEBUG ALL GATHERED VARIABLE
- debug:
    msg: 
      - "Node: {{ k8s_node_name }}"
      - "  - Kubeadm version: {{ kubeadm_version }}"
      - "  - Kubelet version: {{ kubelet_version }}"